// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/pvz/item_service.proto

package pvz_v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReceptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PvzId         string                 `protobuf:"bytes,1,opt,name=pvzId,proto3" json:"pvzId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReceptionRequest) Reset() {
	*x = CreateReceptionRequest{}
	mi := &file_api_pvz_item_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReceptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReceptionRequest) ProtoMessage() {}

func (x *CreateReceptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pvz_item_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReceptionRequest.ProtoReflect.Descriptor instead.
func (*CreateReceptionRequest) Descriptor() ([]byte, []int) {
	return file_api_pvz_item_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReceptionRequest) GetPvzId() string {
	if x != nil {
		return x.PvzId
	}
	return ""
}

type CreateReceptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DateTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=dateTime,proto3" json:"dateTime,omitempty"`
	PvzID         string                 `protobuf:"bytes,3,opt,name=pvzID,proto3" json:"pvzID,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReceptionResponse) Reset() {
	*x = CreateReceptionResponse{}
	mi := &file_api_pvz_item_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReceptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReceptionResponse) ProtoMessage() {}

func (x *CreateReceptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pvz_item_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReceptionResponse.ProtoReflect.Descriptor instead.
func (*CreateReceptionResponse) Descriptor() ([]byte, []int) {
	return file_api_pvz_item_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReceptionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateReceptionResponse) GetDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTime
	}
	return nil
}

func (x *CreateReceptionResponse) GetPvzID() string {
	if x != nil {
		return x.PvzID
	}
	return ""
}

func (x *CreateReceptionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_pvz_item_service_proto protoreflect.FileDescriptor

const file_api_pvz_item_service_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/pvz/item_service.proto\x12\x06pvz.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"8\n" +
	"\x16CreateReceptionRequest\x12\x1e\n" +
	"\x05pvzId\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x05pvzId\"\xa3\x01\n" +
	"\x17CreateReceptionResponse\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\x126\n" +
	"\bdateTime\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bdateTime\x12\x1e\n" +
	"\x05pvzID\x18\x03 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x05pvzID\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status2y\n" +
	"\vItemService\x12j\n" +
	"\x0fCreateReception\x12\x1e.pvz.v1.CreateReceptionRequest\x1a\x1f.pvz.v1.CreateReceptionResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/receptionsB(Z&github.com/webbsalad/pvz/pvz_v1;pvz_v1b\x06proto3"

var (
	file_api_pvz_item_service_proto_rawDescOnce sync.Once
	file_api_pvz_item_service_proto_rawDescData []byte
)

func file_api_pvz_item_service_proto_rawDescGZIP() []byte {
	file_api_pvz_item_service_proto_rawDescOnce.Do(func() {
		file_api_pvz_item_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_pvz_item_service_proto_rawDesc), len(file_api_pvz_item_service_proto_rawDesc)))
	})
	return file_api_pvz_item_service_proto_rawDescData
}

var file_api_pvz_item_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_pvz_item_service_proto_goTypes = []any{
	(*CreateReceptionRequest)(nil),  // 0: pvz.v1.CreateReceptionRequest
	(*CreateReceptionResponse)(nil), // 1: pvz.v1.CreateReceptionResponse
	(*timestamppb.Timestamp)(nil),   // 2: google.protobuf.Timestamp
}
var file_api_pvz_item_service_proto_depIdxs = []int32{
	2, // 0: pvz.v1.CreateReceptionResponse.dateTime:type_name -> google.protobuf.Timestamp
	0, // 1: pvz.v1.ItemService.CreateReception:input_type -> pvz.v1.CreateReceptionRequest
	1, // 2: pvz.v1.ItemService.CreateReception:output_type -> pvz.v1.CreateReceptionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_pvz_item_service_proto_init() }
func file_api_pvz_item_service_proto_init() {
	if File_api_pvz_item_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_pvz_item_service_proto_rawDesc), len(file_api_pvz_item_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pvz_item_service_proto_goTypes,
		DependencyIndexes: file_api_pvz_item_service_proto_depIdxs,
		MessageInfos:      file_api_pvz_item_service_proto_msgTypes,
	}.Build()
	File_api_pvz_item_service_proto = out.File
	file_api_pvz_item_service_proto_goTypes = nil
	file_api_pvz_item_service_proto_depIdxs = nil
}
