// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/pvz/login_service.proto

package pvz_v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DummyLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DummyLoginRequest) Reset() {
	*x = DummyLoginRequest{}
	mi := &file_api_pvz_login_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DummyLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DummyLoginRequest) ProtoMessage() {}

func (x *DummyLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pvz_login_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DummyLoginRequest.ProtoReflect.Descriptor instead.
func (*DummyLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_pvz_login_service_proto_rawDescGZIP(), []int{0}
}

func (x *DummyLoginRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type DummyLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DummyLoginResponse) Reset() {
	*x = DummyLoginResponse{}
	mi := &file_api_pvz_login_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DummyLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DummyLoginResponse) ProtoMessage() {}

func (x *DummyLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pvz_login_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DummyLoginResponse.ProtoReflect.Descriptor instead.
func (*DummyLoginResponse) Descriptor() ([]byte, []int) {
	return file_api_pvz_login_service_proto_rawDescGZIP(), []int{1}
}

func (x *DummyLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_pvz_login_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pvz_login_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_pvz_login_service_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_pvz_login_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pvz_login_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_pvz_login_service_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_pvz_login_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pvz_login_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_pvz_login_service_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_pvz_login_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pvz_login_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_pvz_login_service_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_api_pvz_login_service_proto protoreflect.FileDescriptor

const file_api_pvz_login_service_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/pvz/login_service.proto\x12\x06pvz.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"'\n" +
	"\x11DummyLoginRequest\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\"*\n" +
	"\x12DummyLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"`\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"_\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\x12\x1d\n" +
	"\x05email\x18\x02 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"I\n" +
	"\fLoginRequest\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\x89\x02\n" +
	"\fLoginService\x12[\n" +
	"\n" +
	"DummyLogin\x12\x19.pvz.v1.DummyLoginRequest\x1a\x1a.pvz.v1.DummyLoginResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/dummyLogin\x12S\n" +
	"\bRegister\x12\x17.pvz.v1.RegisterRequest\x1a\x18.pvz.v1.RegisterResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/register\x12G\n" +
	"\x05Login\x12\x14.pvz.v1.LoginRequest\x1a\x15.pvz.v1.LoginResponse\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/loginB(Z&github.com/webbsalad/pvz/pvz_v1;pvz_v1b\x06proto3"

var (
	file_api_pvz_login_service_proto_rawDescOnce sync.Once
	file_api_pvz_login_service_proto_rawDescData []byte
)

func file_api_pvz_login_service_proto_rawDescGZIP() []byte {
	file_api_pvz_login_service_proto_rawDescOnce.Do(func() {
		file_api_pvz_login_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_pvz_login_service_proto_rawDesc), len(file_api_pvz_login_service_proto_rawDesc)))
	})
	return file_api_pvz_login_service_proto_rawDescData
}

var file_api_pvz_login_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_pvz_login_service_proto_goTypes = []any{
	(*DummyLoginRequest)(nil),  // 0: pvz.v1.DummyLoginRequest
	(*DummyLoginResponse)(nil), // 1: pvz.v1.DummyLoginResponse
	(*RegisterRequest)(nil),    // 2: pvz.v1.RegisterRequest
	(*RegisterResponse)(nil),   // 3: pvz.v1.RegisterResponse
	(*LoginRequest)(nil),       // 4: pvz.v1.LoginRequest
	(*LoginResponse)(nil),      // 5: pvz.v1.LoginResponse
}
var file_api_pvz_login_service_proto_depIdxs = []int32{
	0, // 0: pvz.v1.LoginService.DummyLogin:input_type -> pvz.v1.DummyLoginRequest
	2, // 1: pvz.v1.LoginService.Register:input_type -> pvz.v1.RegisterRequest
	4, // 2: pvz.v1.LoginService.Login:input_type -> pvz.v1.LoginRequest
	1, // 3: pvz.v1.LoginService.DummyLogin:output_type -> pvz.v1.DummyLoginResponse
	3, // 4: pvz.v1.LoginService.Register:output_type -> pvz.v1.RegisterResponse
	5, // 5: pvz.v1.LoginService.Login:output_type -> pvz.v1.LoginResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_pvz_login_service_proto_init() }
func file_api_pvz_login_service_proto_init() {
	if File_api_pvz_login_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_pvz_login_service_proto_rawDesc), len(file_api_pvz_login_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pvz_login_service_proto_goTypes,
		DependencyIndexes: file_api_pvz_login_service_proto_depIdxs,
		MessageInfos:      file_api_pvz_login_service_proto_msgTypes,
	}.Build()
	File_api_pvz_login_service_proto = out.File
	file_api_pvz_login_service_proto_goTypes = nil
	file_api_pvz_login_service_proto_depIdxs = nil
}
