// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/pvz/login_service.proto

package pvz_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DummyLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DummyLoginRequest) Reset() {
	*x = DummyLoginRequest{}
	mi := &file_api_pvz_login_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DummyLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DummyLoginRequest) ProtoMessage() {}

func (x *DummyLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pvz_login_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DummyLoginRequest.ProtoReflect.Descriptor instead.
func (*DummyLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_pvz_login_service_proto_rawDescGZIP(), []int{0}
}

func (x *DummyLoginRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type DummyLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DummyLoginResponse) Reset() {
	*x = DummyLoginResponse{}
	mi := &file_api_pvz_login_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DummyLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DummyLoginResponse) ProtoMessage() {}

func (x *DummyLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pvz_login_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DummyLoginResponse.ProtoReflect.Descriptor instead.
func (*DummyLoginResponse) Descriptor() ([]byte, []int) {
	return file_api_pvz_login_service_proto_rawDescGZIP(), []int{1}
}

func (x *DummyLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_api_pvz_login_service_proto protoreflect.FileDescriptor

const file_api_pvz_login_service_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/pvz/login_service.proto\x12\x06pvz.v1\x1a\x1cgoogle/api/annotations.proto\"'\n" +
	"\x11DummyLoginRequest\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\"*\n" +
	"\x12DummyLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2k\n" +
	"\fLoginService\x12[\n" +
	"\n" +
	"DummyLogin\x12\x19.pvz.v1.DummyLoginRequest\x1a\x1a.pvz.v1.DummyLoginResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/dummyLoginB(Z&github.com/webbsalad/pvz/pvz_v1;pvz_v1b\x06proto3"

var (
	file_api_pvz_login_service_proto_rawDescOnce sync.Once
	file_api_pvz_login_service_proto_rawDescData []byte
)

func file_api_pvz_login_service_proto_rawDescGZIP() []byte {
	file_api_pvz_login_service_proto_rawDescOnce.Do(func() {
		file_api_pvz_login_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_pvz_login_service_proto_rawDesc), len(file_api_pvz_login_service_proto_rawDesc)))
	})
	return file_api_pvz_login_service_proto_rawDescData
}

var file_api_pvz_login_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_pvz_login_service_proto_goTypes = []any{
	(*DummyLoginRequest)(nil),  // 0: pvz.v1.DummyLoginRequest
	(*DummyLoginResponse)(nil), // 1: pvz.v1.DummyLoginResponse
}
var file_api_pvz_login_service_proto_depIdxs = []int32{
	0, // 0: pvz.v1.LoginService.DummyLogin:input_type -> pvz.v1.DummyLoginRequest
	1, // 1: pvz.v1.LoginService.DummyLogin:output_type -> pvz.v1.DummyLoginResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_pvz_login_service_proto_init() }
func file_api_pvz_login_service_proto_init() {
	if File_api_pvz_login_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_pvz_login_service_proto_rawDesc), len(file_api_pvz_login_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pvz_login_service_proto_goTypes,
		DependencyIndexes: file_api_pvz_login_service_proto_depIdxs,
		MessageInfos:      file_api_pvz_login_service_proto_msgTypes,
	}.Build()
	File_api_pvz_login_service_proto = out.File
	file_api_pvz_login_service_proto_goTypes = nil
	file_api_pvz_login_service_proto_depIdxs = nil
}
