// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/pvz/reception_service.proto

package pvz_v1

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// ReceptionServiceClient is the client API for ReceptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReceptionServiceClient interface {
}

type receptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReceptionServiceClient(cc grpc.ClientConnInterface) ReceptionServiceClient {
	return &receptionServiceClient{cc}
}

// ReceptionServiceServer is the server API for ReceptionService service.
// All implementations must embed UnimplementedReceptionServiceServer
// for forward compatibility.
type ReceptionServiceServer interface {
	mustEmbedUnimplementedReceptionServiceServer()
}

// UnimplementedReceptionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReceptionServiceServer struct{}

func (UnimplementedReceptionServiceServer) mustEmbedUnimplementedReceptionServiceServer() {}
func (UnimplementedReceptionServiceServer) testEmbeddedByValue()                          {}

// UnsafeReceptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReceptionServiceServer will
// result in compilation errors.
type UnsafeReceptionServiceServer interface {
	mustEmbedUnimplementedReceptionServiceServer()
}

func RegisterReceptionServiceServer(s grpc.ServiceRegistrar, srv ReceptionServiceServer) {
	// If the following call pancis, it indicates UnimplementedReceptionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReceptionService_ServiceDesc, srv)
}

// ReceptionService_ServiceDesc is the grpc.ServiceDesc for ReceptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReceptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pvz.v1.ReceptionService",
	HandlerType: (*ReceptionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "api/pvz/reception_service.proto",
}
